'use strict';
(()=>{
 const $=id=>document.getElementById(id),key='to-be-records-v1';
 let game='pairs',mode='solo',names=['Equipo Sol','Equipo Mar'],points=[0,0],streaks=[0,0],turn=0,done=false,enabled=true,audio=null,records=[],storage=true;
 try{const parsed=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(parsed))records=parsed.filter(r=>['pairs','order','detective','gap','short','transform','memory','visual','listen'].includes(r.game)&&['solo','duel'].includes(r.mode)&&typeof r.name==='string'&&Number.isFinite(r.points)&&r.points>=0).slice(0,90);}catch{storage=false;}
 function sound(kind){if(!enabled)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const tunes={tap:[440],hit:[523,659,784],miss:[260,220],win:[523,659,784,1047]};(tunes[kind]||tunes.tap).forEach((f,i)=>{const t=audio.currentTime+i*.09,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.065,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.17);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.18);});}catch{$('sound-toggle').textContent='Sonido no disponible';enabled=false;$('sound-toggle').setAttribute('aria-pressed','false');}}
 function ranking(){const list=$('ranking-list');list.replaceChildren();const rows=records.filter(r=>r.game===game&&r.mode===mode).sort((a,b)=>b.points-a.points).slice(0,5);if(!rows.length){const li=document.createElement('li');li.textContent='Completa una partida para estrenar el marcador.';list.append(li);}rows.forEach(r=>{const li=document.createElement('li'),name=document.createElement('span'),value=document.createElement('b');name.textContent=r.name;value.textContent=`${r.points} puntos`;li.append(name,value);list.append(li);});$('ranking-note').textContent=storage?'Récords de este juego y modo, guardados solo en este navegador.':'El navegador no permite guardar récords. Puedes seguir jugando; esta clasificación dura durante la sesión.';}
 function board(){const host=$('scoreboard');host.replaceChildren();for(let i=0;i<(mode==='duel'?2:1);i++){const card=document.createElement('div');card.className=`score-player player-${i}${!done&&i===turn?' active':''}`;card.dataset.player=i;const n=document.createElement('b'),p=document.createElement('strong'),s=document.createElement('span');n.textContent=names[i];p.textContent=points[i];p.dataset.points=i;s.textContent=`puntos · racha ${streaks[i]}`;card.append(n,p,s);host.append(card);}$('compact-score').textContent=names.slice(0,mode==='duel'?2:1).map((n,i)=>`${n}: ${points[i]} pts`).join(' · ')+(done?' · Final':mode==='duel'?` · Turno: ${names[turn]}`:'');$('turn-label').textContent=done?(mode==='solo'?'¡Partida terminada!':points[0]===points[1]?'¡Empate! La revancha os espera.':`¡Gana ${names[points[0]>points[1]?0:1]}!`):(mode==='solo'?`A por tu récord, ${names[0]}.`:`Turno de ${names[turn]}`);}
 function feedback(kind){const node=document.querySelector('.game-surface');node.dataset.feedback=kind;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)node.animate([{transform:'scale(1)'},{transform:kind==='hit'?'scale(1.012)':'translateX(-4px)'},{transform:'none'}],{duration:300});sound(kind);}
 window.matchGame={
 reset(g){game=g;points=[0,0];streaks=[0,0];turn=0;done=false;$('score-event').textContent='';document.querySelector('.game-surface').removeAttribute('data-feedback');board();ranking();},
 fail(){if(done)return;streaks[turn]=0;board();$('score-event').textContent='La racha vuelve a 0. Sigue intentándolo.';feedback('miss');},
 award(clean,correct=true){if(done)return;const who=turn,bonus=clean&&correct?Math.min(streaks[who]*10,50):0;const gain=correct?(clean?100+bonus:30):0;points[who]+=gain;streaks[who]=clean&&correct?streaks[who]+1:0;$('score-event').textContent=`${names[who]}: +${gain} puntos${bonus?` (incluye ${bonus} de bonus)`:''}.`;if(mode==='duel')turn=1-turn;board();feedback(correct?'hit':'miss');},
 finish(){if(done)return;done=true;board();for(let i=0;i<(mode==='duel'?2:1);i++)records.push({game,mode,name:names[i],points:points[i]});const kept=[];for(const g of ['pairs','order','detective','gap','short','transform','memory','visual','listen'])for(const m of ['solo','duel'])kept.push(...records.filter(r=>r.game===g&&r.mode===m).sort((a,b)=>b.points-a.points).slice(0,5));records=kept;try{localStorage.setItem(key,JSON.stringify(records));}catch{storage=false;}ranking();sound('win');},
 speak(text){
  if(!enabled){$('game-feedback').textContent='El sonido está silenciado. Actívalo o pulsa Mostrar frase.';return;}
  if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){$('game-feedback').textContent='Voz no disponible. Pulsa Mostrar frase para continuar.';return;}
  speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-GB';utterance.rate=.8;
  utterance.onerror=e=>{if(e.error==='canceled'||e.error==='interrupted'||game!=='listen')return;$('game-feedback').textContent='No se pudo reproducir. Puedes usar Mostrar frase.';};speechSynthesis.speak(utterance);
 },
 tap(){sound('tap');}
 };
 $('sound-toggle').onclick=()=>{enabled=!enabled;if(!enabled)window.speechSynthesis?.cancel();$('sound-toggle').setAttribute('aria-pressed',String(enabled));$('sound-toggle').textContent=enabled?'♪ Sonido activado':'Sonido silenciado';if(enabled)sound('hit');};
 $('match-mode').onchange=()=>{$('player-two-label').hidden=$('match-mode').value!=='duel';};
 $('apply-match').onclick=()=>{mode=$('match-mode').value;names=[$('player-one').value.trim()||'Equipo Sol',$('player-two').value.trim()||'Equipo Mar'];$('game-restart').click();sound('tap');};
 document.querySelector('#game-content').addEventListener('click',e=>{if(e.target.closest('button:not(:disabled)'))sound('tap');});
})();
