const{chromium}=require('playwright');const path=require('path');const fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve('piezas/ingles-to-be/web/index.html'));await p.locator('[data-step="6"]').click();
const verbs=['am','are','is','is','is','are','are','are'];await p.locator('.verb-targets').getByRole('button',{name:'am',exact:true}).click();if(!(await p.locator('#game-feedback').innerText()).includes('Primero'))throw Error('pair no selection');await p.locator('[data-pair="0"]').click();await p.locator('.verb-targets').getByRole('button',{name:'is',exact:true}).click();await p.locator('[data-pair="0"]').click();for(let i=0;i<8;i++){await p.locator(`[data-pair="${i}"]`).click();await p.locator('.verb-targets').getByRole('button',{name:verbs[i],exact:true}).click();}if(await p.locator('.game-result').innerText()!=='7 de 8')throw Error('pairs score');await p.locator('#game-restart').click();if(await p.locator('[data-pair]').count()!==8)throw Error('pairs reset');
await p.locator('[data-game="order"]').click();await p.getByRole('button',{name:'Comprobar',exact:true}).click();if(!(await p.locator('#game-feedback').innerText()).includes('todas'))throw Error('incomplete');
const translations={'Estoy contento/a.':['I','am','happy','.'],'Ella está preparada.':['She','is','ready','.'],'¿Estás preparado/a?':['Are','you','ready','?'],'No estamos cansados/as.':['We','are','not','tired','.'],'¿Está él contento?':['Is','he','happy','?'],'No están preparados/as.':['They','are','not','ready','.']};
for(let i=0;i<6;i++){const hint=await p.locator('#game-help').innerText();const key=Object.keys(translations).find(k=>hint.includes(k));const words=translations[key];if(i===0){for(const w of [...words].reverse())await p.locator('.word-bank').getByRole('button',{name:w,exact:true}).click();await p.getByRole('button',{name:'Comprobar',exact:true}).click();if(!(await p.locator('#game-feedback').innerText()).includes('Todavía'))throw Error('bad order');await p.getByRole('button',{name:'Vaciar',exact:true}).click();await p.locator('.word-bank').getByRole('button',{name:words[0],exact:true}).click();await p.getByRole('button',{name:'Deshacer',exact:true}).click();if(await p.locator('.sentence-slot button').count())throw Error('undo');}for(const w of words)await p.locator('.word-bank').getByRole('button',{name:w,exact:true}).click();await p.getByRole('button',{name:'Comprobar',exact:true}).click();await p.locator('#game-actions .primary').click();}if(await p.locator('.game-result').innerText()!=='5 de 6')throw Error('order score');
await p.locator('[data-game="detective"]').click();for(let i=0;i<8;i++){const s=await p.locator('.detective-sentence').innerText();const ok=['Are you ready?','I am not tired.','Is he ready?','It is small.'].includes(s);await p.locator(`[data-verdict="${i===0?!ok:ok}"]`).click();if(!(await p.locator('#game-feedback').innerText()).length)throw Error('feedback');await p.locator('#game-actions .primary').click();}if(await p.locator('.game-result').innerText()!=='7 de 8')throw Error('detective score');
for(const width of [320,375,414,768,1280]){await p.setViewportSize({width,height:900});for(const g of ['pairs','order','detective']){await p.locator(`[data-game="${g}"]`).click();if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('overflow');await p.screenshot({path:`piezas/ingles-to-be/qa/games-${g}-${width}.png`,fullPage:true,animations:'disabled'});}}
await p.locator('[data-step="0"]').click();if(!await p.locator('#lesson').isVisible())throw Error('lesson return');await p.locator('[data-step="5"]').click();if(!await p.locator('#practice').isVisible())throw Error('practice return');if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('piezas/ingles-to-be/qa/games-results.json',JSON.stringify({passed:true,rounds:22,viewports:[320,375,414,768,1280],checks:['three complete games','wrong answers and first attempt scoring','pairs reselection','empty answer','undo','reset','lesson and quiz navigation'],errors},null,2));await b.close();console.log('PASS: 22 rounds, errors, reset, scores, 15 responsive views, lesson navigation.');})();
