const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve('ingles-to-be/web/index.html')+'#juegos');await p.locator('#sound-toggle').click();
const select=async g=>p.locator(`[data-game="${g}"]`).click();
await select('memory');await p.locator('[data-card]').nth(0).click();const first=await p.locator('[data-card]').nth(0).innerText();const partner=await p.evaluate(t=>englishBank.memory.find(row=>row.includes(t)).find(x=>x!==t),first);
let wrong;
for(let i=1;i<12;i++){await p.locator('[data-card]').nth(i).click();if(!(await p.locator('#game-feedback').innerText()).includes('Correcto')){wrong=true;break;}await select('memory');await p.locator('[data-card]').nth(0).click();}
if(!wrong)throw Error('No mismatch');if(await p.getByRole('button',{name:'Ocultar y seguir'}).count())throw Error('Manual control remains');if(await p.locator('[data-card]:not(:disabled)').count())throw Error('Third card allowed');await p.waitForTimeout(1950);if(await p.locator('[data-card][aria-pressed="true"]').count())throw Error('Not hidden');
await p.locator('[data-card]').nth(0).click();await p.locator('[data-card]').nth(1).click();await select('visual');await p.waitForTimeout(1950);if(await p.locator('#game-title').innerText()!=='Mira y completa')throw Error('Old timer changed game');
for(const game of ['visual','listen']){await select(game);for(let i=0;i<8;i++){
 if(game==='visual'){const text=await p.locator('.detective-sentence').innerText();const answer=text.startsWith('It')?'is':'are';if(i===0)await p.locator('.choice-options').getByRole('button',{name:'am',exact:true}).click();await p.locator('.choice-options').getByRole('button',{name:answer,exact:true}).click();}
 else{await p.getByRole('button',{name:'Escuchar frase'}).click();if(!(await p.locator('#game-feedback').innerText()).includes('silenciado'))throw Error('Mute fallback');await p.getByRole('button',{name:'Mostrar frase'}).click();const text=await p.locator('.detective-sentence').innerText();const id=await p.evaluate(t=>englishBank.listen.find(x=>x.sentence===t).id,text);if(i===0)await p.locator(`[data-scene]:not([data-scene="${id}"])`).first().click();await p.locator(`[data-scene="${id}"]`).click();}
 await p.locator('#game-actions .primary').click();}
 if(await p.locator('.game-result').innerText()!=='7 de 8')throw Error('Score');}
await select('listen');await p.locator('#sound-toggle').click();await p.evaluate(()=>{window.voiceCalls=[];speechSynthesis.speak=u=>voiceCalls.push([u.text,u.lang]);});await p.getByRole('button',{name:'Escuchar frase'}).click();if(await p.evaluate(()=>voiceCalls.length)!==1)throw Error('Speech not invoked');
for(const width of [320,375,768,1280]){await p.setViewportSize({width,height:900});for(const game of ['visual','listen']){await select(game);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow '+width);if(width===375){await p.locator('#game-title').scrollIntoViewIfNeeded();await p.screenshot({path:`ingles-to-be/qa/visual-audio-${game}-375.png`});}}}
if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('ingles-to-be/qa/visual-audio-results.json',JSON.stringify({passed:true,memoryAutomatic:true,timerCancelled:true,completeGames:['visual','listen'],speechInvocation:true,muteFallback:true,widths:[320,375,768,1280],errors,limitations:['Voz invocada con stub; sin escucha humana ni iPhone físico.']},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
